import { v4 as uuid } from "uuid";

/**
 * Product Database can be added here.
 * You can add products of your wish with different attributes
 * */

export const products = [
  {
    _id: uuid(),
    title: "Women Ethnic Wear",
    desc: "If you love flaunting ethnic print kurtas, then this whole set is for you. It is a set of two, a straight kurta with trousers. Crafted with pure cotton and pastel colour makes it soft to touch and apt to wear in any season.",
    price: "500",
    sell_price: "200",
    rating: "4",
    imageUrl: "https://i.ibb.co/qBNTfbw/Women-Ethnic-Wear.webp",
    categoryName: "Women",
  },

  {
    _id: uuid(),
    title: "Women's Jogger",
    desc: "Peach medium wash 5-pocket high-rise cropped jeans, clean look, light fade, has a button and zip closure, and waistband with belt loops",
    price: "900",
    sell_price: "750",
    rating: "3",
    imageUrl: "https://i.ibb.co/BP021tV/Women-1.webp",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    title: "Men's Sweater",
    desc: "Navy Blue solid sweater, has a round neck, long sleeves, and ribbed hem",
    price: "1100",
    sell_price: "1050",
    rating: "5",
    imageUrl: "https://i.ibb.co/26KFzDB/Winter-2.webp",
    categoryName: "Winter",
  },
  {
    _id: uuid(),
    title: "Women's Denim Jacket",
    desc: "Blue floral printed denim jacket, has a spread collar,2 flap pockets, has a button closure, long sleeves, straight hemline, without lining",
    price: "1000",
    sell_price: "850",
    rating: "2",
    imageUrl: "https://i.ibb.co/7kVtpGd/Winter-1.webp",
    categoryName: "Winter",
  },
  {
    _id: uuid(),
    title: "Men's T-Shirt",
    desc: "White solid T-shirt, has a round neck, and short sleeves",
    price: "500",
    sell_price: "450",
    rating: "1",
    imageUrl: "https://i.ibb.co/ryTb9gy/Summer-2.webp",
    categoryName: "Summer",
  },
  {
    _id: uuid(),
    title: "Women Straight Gown",
    desc: "Look feminine and chic by donning this alluring dress to your next outing. It is designed with a lovely V-neck and three-quarter regular sleeves for enhanced appeal.",
    price: "600",
    sell_price: "500",
    rating: "4",
    imageUrl: "https://i.ibb.co/f2W2j9B/Women-2.webp",
    categoryName: "Women",
  },
  {
    _id: uuid(),
    title: "Kid's Shirt",
    desc: "Olive green and navy blue checked opaque Casual shirt ,has a spread collar, button placket, long regular sleeves, curved hem",
    price: "1200",
    sell_price: "850",
    rating: "5",
    imageUrl: "https://i.ibb.co/X2DWXjF/Kids-2.webp",
    categoryName: "Kids",
  },
  {
    _id: uuid(),
    title: "Women's T-Shirt",
    desc: "White and navy blue Tshirt for women,Floral printed , Regular length , Round neck , Short, regular sleeves , Knitted cotton fabric",
    price: "700",
    sell_price: "550",
    rating: "4",
    imageUrl: "https://i.ibb.co/cgkP1W9/Summer-1.webp",
    categoryName: "Summer",
  },
  {
    _id: uuid(),
    title: "Mens Jacket",
    desc: "Brown solid bomber, has a mock collar, 3 pockets ,has a zip closure, long sleeves, straight hemline, polyester lining",
    price: "1200",
    sell_price: "1050",
    rating: "5",
    imageUrl: "https://i.ibb.co/PzrCCm2/Mens-3.webp",
    categoryName: "Mens",
  },

  {
    _id: uuid(),
    title: "Mens Shirt",
    desc: "Black and teal blue striped casual shirt, has a spread collar, long sleeves, button placket, curved hem, and 1 patch pocket",
    price: "900",
    sell_price: "750",
    rating: "3",
    imageUrl: "https://i.ibb.co/5Rg5GXv/Mens-1.webp",
    categoryName: "Mens",
  },
  {
    _id: uuid(),
    title: "Kid's Tracksuit",
    desc: "Active tracksuit , Rapid Dry Technology wicks sweat & makes the fabric dry fast , Anti-microbial technology prevents the growth of odor-causing microbes keeping you fresh & hygienic all day Contrast piping detail on sleeves",
    price: "2000",
    sell_price: "1750",
    rating: "4",
    imageUrl: "https://i.ibb.co/0hpC13H/kids-3.webp",
    categoryName: "Kids",
  },
  {
    _id: uuid(),
    title: "Kid's Top",
    desc: "Cropped, boxy-style top in soft cotton jersey with a print motif. Narrow trim around the neckline, dropped shoulders and short, wide sleeves.",
    price: "1200",
    sell_price: "750",
    rating: "4",
    imageUrl: "https://i.ibb.co/H7Qd5b4/Kids-1.webp",
    categoryName: "Kids",
  },

  {
    _id: uuid(),
    title: "Mens Shirt",
    desc: "White and teal blue striped casual shirt, has a spread collar, long sleeves, button placket, curved hem, and 1 patch pocket",
    price: "800",
    sell_price: "750",
    rating: "4",
    imageUrl: "https://i.ibb.co/sVVmjZG/Mens-2.webp",
    categoryName: "Mens",
  },
];
